services:
  safety-service:
    container_name: safety-service
    build:
      context: ../..
      dockerfile: workers/safety/Dockerfile
    environment:
      - KAFKA_BROKERS=84.201.147.126:9092
    restart: unless-stopped
    command: ["python", "-u", "workers/safety/safety_worker.py"]
