services:
  ad-service:
    container_name: ad-service
    build:
      context: ../..
      dockerfile: workers/ad/Dockerfile
    environment:
      - KAFKA_BROKERS=84.201.147.126:9092
    restart: unless-stopped
    command: ["python", "-u", "workers/ad/ad_filter_worker.py"]
