services:
  offtopic-service:
    container_name: offtopic-service
    build:
      context: ../..
      dockerfile: workers/offtopic/Dockerfile
    environment:
      - KAFKA_BROKERS=84.201.147.126:9092
    restart: unless-stopped
    command: ["python", "-u", "workers/offtopic/off_topic_worker.py"]
